# Generated by Django 4.1.3 on 2022-11-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='lms.curator')),
            ],
        ),
    ]
